/**
 * BAZAR KATALOQU — kateqoriyalar, tədarükçülər, məhsullar. NÜMUNƏ MƏLUMATDIR.
 *
 * ═══ NİYƏ KOD MODULU, NİYƏ BAZA DEYİL (HƏLƏ) ══════════════════════════
 * Server və klient EYNİ faylı gətirir (`lib/kreditSertler.js` presedenti):
 *   • server (api/bazar.js) qiyməti, təchizatçını və maliyyələşmə bayrağını
 *     YALNIZ buradan oxuyur — klientin göndərdiyi rəqəm heç vaxt bağlayıcı
 *     deyil (bax: lib/bazar/sifaris.js → sebetiHesabla);
 *   • klient kataloqu şəbəkəsiz göstərir — pilot rayonlarda internet zəifdir
 *     və "kataloq yüklənir" ekranı fermeri itirir;
 *   • sifariş sətrinə məhsulun ADI, QİYMƏTİ və TƏCHİZATÇISI SURƏT kimi yazılır
 *     (kredit qərarındakı `decision_inputs` prinsipi): kataloq sabah dəyişsə
 *     də dünənki sifariş izah oluna bilir. `KATALOQ_VERSIYA` da sifarişə düşür.
 *
 * FAZA 2: tədarükçü özü qiymət yazanda bu massiv `marketplace_products`
 * cədvəlinə köçür; `mehsulTap()`/`tedarukcuTap()` imzası eyni qalır, ona görə
 * api/ və src/ dəyişmir — yalnız bu modulun içi.
 *
 * ═══ NÜMUNƏ ══════════════════════════════════════════════════════════════
 * Bütün qiymətlər, tədarükçü adları, reytinqlər və stok halları NÜMUNƏDİR
 * (`NUMUNE = true`, UI-da "Qiymətlər nümunədir" qeydi görünür). Bitki
 * mühafizəsi məhsulları ümumi sinif adı ilə verilir — konkret preparat və
 * doza YAZILMIR (layihə qaydası: qeydiyyat AQTA reyestrindədir, doza etiketə
 * görə; bax: README → "preparat və doza verilmir").
 *
 * Məhsul adları və təsvirlər MƏLUMATDIR (rayon adları kimi) — üç dilə
 * tərcümə olunmur; UI etiketləri isə i18n açarlarıdır (`bazar.*`).
 */

export const NUMUNE = true;
export const KATALOQ_VERSIYA = "numune-2026-09";

/**
 * @typedef {object} Kateqoriya
 * @property {string} kod       sabit kimlik (URL, sifariş sətri)
 * @property {string} adKey     i18n açarı
 * @property {string} ikon      components/icons.js-dəki ad
 * @property {string} ton       features/bazar/tonlar.js-dəki rəng cütü
 * @property {string[]} sozler  axtarış üçün əlavə sözlər (aksentsiz)
 */

/** @type {Kateqoriya[]} */
export const KATEQORIYALAR = [
  { kod: "toxum", adKey: "bazar.kat.toxum", ikon: "Sprout", ton: "moss", sozler: ["toxum", "ting", "seed", "семена", "саженец"] },
  { kod: "gubre", adKey: "bazar.kat.gubre", ikon: "FlaskConical", ton: "wheat", sozler: ["gubre", "fertilizer", "удобрение", "azot", "npk"] },
  { kod: "muhafize", adKey: "bazar.kat.muhafize", ikon: "Bug", ton: "clay", sozler: ["muhafize", "dermanlama", "pesticide", "защита", "fungisid", "insektisid", "herbisid"] },
  { kod: "suvarma", adKey: "bazar.kat.suvarma", ikon: "Droplets", ton: "sky", sozler: ["suvarma", "damci", "irrigation", "полив", "nasos", "boru"] },
  { kod: "heyvandarliq", adKey: "bazar.kat.heyvandarliq", ikon: "Beef", ton: "sand", sozler: ["heyvandarliq", "yem", "livestock", "животноводство", "mal", "qoyun"] },
  { kod: "texnika", adKey: "bazar.kat.texnika", ikon: "Tractor", ton: "steel", sozler: ["texnika", "avadanliq", "traktor", "machinery", "техника"] },
  { kod: "xidmet", adKey: "bazar.kat.xidmet", ikon: "Wrench", ton: "plum", sozler: ["xidmet", "service", "услуга", "kombayn", "analiz"] },
  { kod: "diger", adKey: "bazar.kat.diger", ikon: "Package", ton: "mist", sozler: ["diger", "other", "другое"] },
];

/** Aran zonası — bir neçə tədarükçünün çatdırılma əhatəsi */
const ARAN = [
  "berde", "agcabedi", "agdam", "beyleqan", "imisli", "saatli", "sabirabad", "kurdemir",
  "ucar", "zerdab", "goycay", "yevlax", "mingecevir", "agdas", "haciqabul", "sirvan", "salyan",
];
const QERB = ["semkir", "gence", "goranboy", "samux", "tovuz", "qazax"];

/**
 * @typedef {object} Tedarukcu
 * @property {string} kod
 * @property {string} ad
 * @property {boolean} tesdiqli       "AgriFin Verified" — sənədləri yoxlanılıb
 * @property {number|null} reytinq    1–5; rəy yoxdursa null
 * @property {number} reySayi
 * @property {number} il              fəaliyyətə başlama ili
 * @property {"*"|string[]} rayonlar  çatdırılma əhatəsi (rayon kodları)
 * @property {[number, number]} catdirilmaGun  gözlənilən çatdırılma, gün (min, max)
 * @property {number} catdirilmaHaqqi çatdırılma haqqı (₼); 0 = pulsuz
 * @property {number} pulsuzHedd      bu məbləğdən yuxarı sifarişdə haqq 0
 * @property {string} haqqinda
 */

/** @type {Tedarukcu[]} */
export const TEDARUKCULER = [
  {
    kod: "agrosupply",
    ad: "AgroSupply MMC",
    tesdiqli: true,
    reytinq: 4.8,
    reySayi: 126,
    il: 2014,
    rayonlar: "*",
    catdirilmaGun: [2, 4],
    catdirilmaHaqqi: 15,
    pulsuzHedd: 500,
    haqqinda:
      "Gübrə və aqro-material distribütoru. Bakı və Gəncədə anbar, respublikanın bütün rayonlarına çatdırılma. Sertifikatlı mənşə sənədləri hər partiya ilə verilir.",
  },
  {
    kod: "azertoxum",
    ad: "AzərToxum ASC",
    tesdiqli: true,
    reytinq: 4.7,
    reySayi: 89,
    il: 2009,
    rayonlar: "*",
    catdirilmaGun: [3, 6],
    catdirilmaHaqqi: 0,
    pulsuzHedd: 0,
    haqqinda:
      "Toxumçuluq və tinglik təsərrüfatı. Yerli və seçilmiş sortlar, reproduksiya sənədi ilə. Bütün rayonlara pulsuz çatdırılma.",
  },
  {
    kod: "aqrokimya",
    ad: "Aqrokimya Servis",
    tesdiqli: true,
    reytinq: 4.5,
    reySayi: 54,
    il: 2017,
    rayonlar: [...ARAN, ...QERB],
    catdirilmaGun: [2, 3],
    catdirilmaHaqqi: 12,
    pulsuzHedd: 300,
    haqqinda:
      "Bitki mühafizəsi və yarpaq gübrələri. Yalnız dövlət reyestrində qeydiyyatlı preparatlar; qablaşmada reyestr nömrəsi və etiket norması.",
  },
  {
    kod: "suvarmatex",
    ad: "SuvarmaTex",
    tesdiqli: true,
    reytinq: 4.6,
    reySayi: 41,
    il: 2016,
    rayonlar: "*",
    catdirilmaGun: [3, 7],
    catdirilmaHaqqi: 25,
    pulsuzHedd: 800,
    haqqinda:
      "Damcı və yağış suvarma sistemləri: layihələndirmə, material, quraşdırma. Sahə ölçüsünə görə pulsuz hesablama.",
  },
  {
    kod: "ferma-market",
    ad: "Ferma Market",
    tesdiqli: false,
    reytinq: 4.2,
    reySayi: 18,
    il: 2021,
    rayonlar: ARAN,
    catdirilmaGun: [1, 3],
    catdirilmaHaqqi: 10,
    pulsuzHedd: 200,
    haqqinda: "Bərdə mərkəzli aqro-dükan: yem, alət, qablaşma. Aran rayonlarına 1–3 gün ərzində çatdırılma.",
  },
  {
    kod: "agrotexnika",
    ad: "AgroTexnika Lizinq",
    tesdiqli: true,
    reytinq: 4.9,
    reySayi: 33,
    il: 2011,
    rayonlar: "*",
    catdirilmaGun: [7, 14],
    catdirilmaHaqqi: 0,
    pulsuzHedd: 0,
    haqqinda:
      "Kiçik və orta təsərrüfat texnikası. Zəmanət 2 il, servis Bakı və Gəncədə. Çatdırılma sifarişdən sonra razılaşdırılır.",
  },
  {
    kod: "aqroxidmet",
    ad: "Aqro Xidmət Kooperativi",
    tesdiqli: false,
    reytinq: 4.4,
    reySayi: 27,
    il: 2019,
    rayonlar: [...QERB, "berde", "yevlax", "goranboy"],
    catdirilmaGun: [1, 5],
    catdirilmaHaqqi: 0,
    pulsuzHedd: 0,
    haqqinda: "Sahə xidmətləri kooperativi: şum, biçin, çiləmə, torpaq analizi. Xidmət tarixi sifarişdən sonra telefonla razılaşdırılır.",
  },
];

/**
 * @typedef {object} Mehsul
 * @property {string} kod            sabit kimlik: URL, səbət, sifariş sətri
 * @property {string} ad             ekranda görünən ad (məlumat, tərcümə olunmur)
 * @property {string} kateqoriya     Kateqoriya.kod
 * @property {string} tedarukcu      Tedarukcu.kod
 * @property {string} brend
 * @property {number} qiymet         vahid qiyməti, ₼ (qəpiklə)
 * @property {string} vahidKey       i18n: bazar.vahid.<açar>
 * @property {string} qablasma
 * @property {number} minSay         minimum sifariş
 * @property {number} maxSay         bir sifarişdə maksimum
 * @property {"var"|"az"|"yoxdur"} stok
 * @property {boolean} maliyye       AgriFin maliyyələşdirməsinə açıqdır
 * @property {boolean} orijinal      istehsalçı sənədi ilə
 * @property {"*"|string[]} rayonlar çatdırılma əhatəsi (tədarükçüdən fərqlənə bilər)
 * @property {string[]} bitkiler     hansı bitkilər üçün (tövsiyə sıralaması)
 * @property {string} tesvir
 * @property {string} tetbiq
 * @property {string} elaveTarixi    YYYY-MM-DD — "Yeni məhsullar" sıralaması
 * @property {number} populyarliq    0–100 — "Tövsiyə olunan" sıralamasının bir hissəsi
 * @property {{nov: "bitki", kod: string} | {nov: "yuva"}} sekil
 *   "bitki" → mövcud bitki fotosu (toxum/ting); "yuva" → asset yuvası
 *   (src/assets/bazar/<kod>.webp varsa o, yoxdursa neytral yer tutucu)
 */

const BUTUN_BITKILER = ["bugda", "arpa", "qargidali", "pambiq", "kartof", "pomidor", "sogan", "uzum", "alma", "findiq"];

/** @type {Mehsul[]} */
export const MEHSULLAR = [
  // ── Toxum və ting ──────────────────────────────────────────────────────
  {
    kod: "pomidor-toxumu-f1",
    ad: "Pomidor toxumu F1 «Aran» — 1000 toxum",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "AzərToxum",
    qiymet: 110,
    vahidKey: "paket",
    qablasma: "1000 toxumluq hermetik paket",
    minSay: 1,
    maxSay: 200,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["pomidor"],
    tesvir: "Aran zonası üçün seçilmiş, istiyə davamlı F1 hibrid. Cücərmə 95%-dən yuxarı; bir hektara 2–3 paket.",
    tetbiq: "Şitil üsulu: səpin fevral–mart, sahəyə köçürmə aprel. Damcı suvarma ilə ən yaxşı nəticə.",
    elaveTarixi: "2026-08-28",
    populyarliq: 92,
    sekil: { nov: "bitki", kod: "pomidor" },
  },
  {
    kod: "kartof-toxumu-aqra",
    ad: "Toxumluq kartof «Aqra» — 25 kq",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "AzərToxum",
    qiymet: 48,
    vahidKey: "kise",
    qablasma: "25 kq torlu kisə, kalibr 35–55 mm",
    minSay: 4,
    maxSay: 400,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["kartof"],
    tesvir: "Orta tez yetişən sort, 1-ci reproduksiya. Fitosanitar sertifikat partiya ilə verilir.",
    tetbiq: "Səpin mart–aprel, torpaq 8 °C-dən isti olanda. Hektara təxminən 2,5–3 t.",
    elaveTarixi: "2026-08-15",
    populyarliq: 85,
    sekil: { nov: "bitki", kod: "kartof" },
  },
  {
    kod: "qargidali-hibrid-25kq",
    ad: "Qarğıdalı hibrid toxumu — 25 kq (80 000 dən)",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "MaizeLine",
    qiymet: 165,
    vahidKey: "kise",
    qablasma: "25 kq, dərmanlanmış, 80 000 dən",
    minSay: 1,
    maxSay: 120,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["qargidali"],
    tesvir: "Dən və silos üçün orta gec hibrid. Bir kisə təxminən 1 ha üçündür.",
    tetbiq: "Səpin aprel, torpaq 10 °C-dən isti olanda. Suvarma tələb edir.",
    elaveTarixi: "2026-07-30",
    populyarliq: 78,
    sekil: { nov: "bitki", kod: "qargidali" },
  },
  {
    kod: "bugda-toxumu-qobustan",
    ad: "Payızlıq buğda toxumu «Qobustan» — 50 kq",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "AzərToxum",
    qiymet: 42,
    vahidKey: "kise",
    qablasma: "50 kq, 1-ci reproduksiya, dərmanlanmış",
    minSay: 4,
    maxSay: 600,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["bugda"],
    tesvir: "Quraqlığa davamlı yerli sort. Reproduksiya sənədi və analiz vərəqi partiya ilə.",
    tetbiq: "Səpin oktyabr–noyabr. Hektara təxminən 4–5 kisə.",
    elaveTarixi: "2026-09-01",
    populyarliq: 88,
    sekil: { nov: "bitki", kod: "bugda" },
  },
  {
    kod: "arpa-toxumu-50kq",
    ad: "Arpa toxumu «Qarabağ 7» — 50 kq",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "AzərToxum",
    qiymet: 38,
    vahidKey: "kise",
    qablasma: "50 kq, 1-ci reproduksiya",
    minSay: 4,
    maxSay: 600,
    stok: "az",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["arpa"],
    tesvir: "Yem və dən üçün payızlıq arpa. Az stok — bu partiya bitir.",
    tetbiq: "Səpin oktyabr. Hektara təxminən 4 kisə.",
    elaveTarixi: "2026-09-05",
    populyarliq: 61,
    sekil: { nov: "bitki", kod: "arpa" },
  },
  {
    kod: "sogan-toxumu-500q",
    ad: "Soğan toxumu «Masallı yerli» — 500 q",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "AzərToxum",
    qiymet: 34,
    vahidKey: "paket",
    qablasma: "500 q folqa paket",
    minSay: 1,
    maxSay: 100,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["sogan"],
    tesvir: "Yerli, yaxşı saxlanan sort. Hektara 3–4 kq toxum.",
    tetbiq: "Səpin oktyabr (payızlıq) və ya mart (yazlıq).",
    elaveTarixi: "2026-08-10",
    populyarliq: 55,
    sekil: { nov: "bitki", kod: "sogan" },
  },
  {
    kod: "alma-tingi-qala",
    ad: "Alma tingi «Qala» (M9 calaqaltı) — 1 ədəd",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "AzərToxum",
    qiymet: 6.5,
    vahidKey: "eded",
    qablasma: "1 illik ting, açıq kök, 90–120 sm",
    minSay: 50,
    maxSay: 5000,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["alma"],
    tesvir: "İntensiv bağ üçün cırtdan calaqaltı. Hektara 2 500–3 000 ting.",
    tetbiq: "Əkin noyabr və ya mart. Dayaq sistemi və damcı suvarma tələb edir.",
    elaveTarixi: "2026-06-20",
    populyarliq: 47,
    sekil: { nov: "bitki", kod: "alma" },
  },
  {
    kod: "uzum-tingi-rkasiteli",
    ad: "Üzüm tingi «Rkasiteli» — 1 ədəd",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "AzərToxum",
    qiymet: 3.2,
    vahidKey: "eded",
    qablasma: "Calaqlı ting, 1 illik",
    minSay: 100,
    maxSay: 10000,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["uzum"],
    tesvir: "Texniki sort, fillokseraya davamlı calaqaltıda. Hektara 2 200–2 800 ting.",
    tetbiq: "Əkin mart–aprel. Şpaler sistemi tələb edir.",
    elaveTarixi: "2026-06-20",
    populyarliq: 40,
    sekil: { nov: "bitki", kod: "uzum" },
  },
  {
    kod: "findiq-tingi",
    ad: "Fındıq tingi «Ata-baba» — 1 ədəd",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "AzərToxum",
    qiymet: 4.8,
    vahidKey: "eded",
    qablasma: "2 illik ting, açıq kök",
    minSay: 50,
    maxSay: 5000,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["findiq"],
    tesvir: "Zaqatala-Balakən zonasının əsas sortu. Hektara 400–600 ting.",
    tetbiq: "Əkin noyabr–mart. İlk məhsul 4–5-ci il.",
    elaveTarixi: "2026-06-20",
    populyarliq: 38,
    sekil: { nov: "bitki", kod: "findiq" },
  },
  {
    kod: "pambiq-toxumu-25kq",
    ad: "Pambıq toxumu «Gəncə-110» — 25 kq",
    kateqoriya: "toxum",
    tedarukcu: "azertoxum",
    brend: "AzərToxum",
    qiymet: 58,
    vahidKey: "kise",
    qablasma: "25 kq, tüksüzləşdirilmiş, dərmanlanmış",
    minSay: 2,
    maxSay: 300,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: ARAN,
    bitkiler: ["pambiq"],
    tesvir: "Orta lifli yerli sort. Yalnız aran rayonlarına çatdırılır.",
    tetbiq: "Səpin aprel, torpaq 12 °C-dən isti olanda. Hektara 2–3 kisə.",
    elaveTarixi: "2026-07-12",
    populyarliq: 44,
    sekil: { nov: "bitki", kod: "pambiq" },
  },

  // ── Gübrə ──────────────────────────────────────────────────────────────
  {
    kod: "karbamid-46-50kq",
    ad: "Karbamid 46% — 50 kq",
    kateqoriya: "gubre",
    tedarukcu: "agrosupply",
    brend: "AzotAgro",
    qiymet: 39.9,
    vahidKey: "kise",
    qablasma: "50 kq polipropilen kisə, dənəvər",
    minSay: 1,
    maxSay: 500,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: BUTUN_BITKILER,
    tesvir: "Azot 46%. Səpin qabağı və yemləmə üçün universal azot gübrəsi. Mənşə sertifikatı ilə.",
    tetbiq: "Norma torpaq analizinə və bitkiyə görə təyin edilir; suvarma ilə birlikdə daha səmərəlidir.",
    elaveTarixi: "2026-08-20",
    populyarliq: 96,
    sekil: { nov: "yuva" },
  },
  {
    kod: "npk-15-15-15-50kq",
    ad: "NPK 15-15-15 — 50 kq",
    kateqoriya: "gubre",
    tedarukcu: "agrosupply",
    brend: "AzotAgro",
    qiymet: 52.5,
    vahidKey: "kise",
    qablasma: "50 kq kisə, kompleks dənəvər",
    minSay: 1,
    maxSay: 500,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: BUTUN_BITKILER,
    tesvir: "Balanslı azot-fosfor-kalium kompleksi. Səpin qabağı əsas gübrə üçün.",
    tetbiq: "Səpindən əvvəl torpağa qarışdırılır; norma torpaq analizinə görə.",
    elaveTarixi: "2026-08-20",
    populyarliq: 90,
    sekil: { nov: "yuva" },
  },
  {
    kod: "ammonium-nitrat-50kq",
    ad: "Ammonium nitrat 34% — 50 kq",
    kateqoriya: "gubre",
    tedarukcu: "agrosupply",
    brend: "AzotAgro",
    qiymet: 36,
    vahidKey: "kise",
    qablasma: "50 kq kisə",
    minSay: 1,
    maxSay: 500,
    stok: "az",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["bugda", "arpa", "qargidali", "pambiq"],
    tesvir: "Tez təsirli azot gübrəsi, taxılın yaz yemləməsi üçün.",
    tetbiq: "Erkən yaz yemləməsi; norma torpaq analizinə görə.",
    elaveTarixi: "2026-08-20",
    populyarliq: 84,
    sekil: { nov: "yuva" },
  },
  {
    kod: "superfosfat-50kq",
    ad: "Superfosfat sadə — 50 kq",
    kateqoriya: "gubre",
    tedarukcu: "agrosupply",
    brend: "AzotAgro",
    qiymet: 31.5,
    vahidKey: "kise",
    qablasma: "50 kq kisə",
    minSay: 1,
    maxSay: 500,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["bugda", "arpa", "kartof", "sogan"],
    tesvir: "Fosfor mənbəyi, kök sisteminin inkişafı üçün.",
    tetbiq: "Payız şumu altına verilir.",
    elaveTarixi: "2026-08-20",
    populyarliq: 62,
    sekil: { nov: "yuva" },
  },
  {
    kod: "kalium-sulfat-25kq",
    ad: "Kalium sulfat — 25 kq",
    kateqoriya: "gubre",
    tedarukcu: "aqrokimya",
    brend: "BioAqro",
    qiymet: 44,
    vahidKey: "kise",
    qablasma: "25 kq, suda həll olan",
    minSay: 1,
    maxSay: 200,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: [...ARAN, ...QERB],
    bitkiler: ["pomidor", "kartof", "uzum", "alma"],
    tesvir: "Xlorsuz kalium — meyvə keyfiyyəti və saxlanma müddəti üçün. Damcı ilə verilə bilər.",
    tetbiq: "Meyvə bağlama və yetişmə dövründə fertiqasiya ilə.",
    elaveTarixi: "2026-08-25",
    populyarliq: 58,
    sekil: { nov: "yuva" },
  },
  {
    kod: "humat-maye-5l",
    ad: "Maye humat (yarpaq gübrəsi) — 5 L",
    kateqoriya: "gubre",
    tedarukcu: "aqrokimya",
    brend: "BioAqro",
    qiymet: 28,
    vahidKey: "qab",
    qablasma: "5 L kanistr",
    minSay: 1,
    maxSay: 100,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: [...ARAN, ...QERB],
    bitkiler: BUTUN_BITKILER,
    tesvir: "Stimulyator və yarpaq gübrəsi; stresdən sonra bərpa üçün.",
    tetbiq: "Yarpaqdan çiləmə, səhər və ya axşam saatlarında.",
    elaveTarixi: "2026-09-08",
    populyarliq: 66,
    sekil: { nov: "yuva" },
  },
  {
    kod: "mikroelement-1kq",
    ad: "Mikroelement kompleksi (Zn, B, Fe) — 1 kq",
    kateqoriya: "gubre",
    tedarukcu: "aqrokimya",
    brend: "BioAqro",
    qiymet: 19.5,
    vahidKey: "paket",
    qablasma: "1 kq, xelat formasında",
    minSay: 1,
    maxSay: 200,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: [...ARAN, ...QERB],
    bitkiler: ["pomidor", "uzum", "alma", "findiq", "qargidali"],
    tesvir: "Xelat mikroelementlər — sarılıq və çiçək tökülməsinə qarşı.",
    tetbiq: "Yarpaqdan çiləmə, 2–3 dəfə mövsümdə.",
    elaveTarixi: "2026-09-06",
    populyarliq: 50,
    sekil: { nov: "yuva" },
  },

  // ── Bitki mühafizəsi (sinif adı ilə — preparat/doza yazılmır) ─────────
  {
    kod: "fungisid-mis-1kq",
    ad: "Mis əsaslı fungisid (kontakt) — 1 kq",
    kateqoriya: "muhafize",
    tedarukcu: "aqrokimya",
    brend: "Aqrokimya",
    qiymet: 24,
    vahidKey: "paket",
    qablasma: "1 kq, islanan toz",
    minSay: 1,
    maxSay: 200,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: [...ARAN, ...QERB],
    bitkiler: ["pomidor", "kartof", "uzum", "alma"],
    tesvir: "Göbələk xəstəliklərinə qarşı profilaktik kontakt preparat. AQTA reyestr nömrəsi qablaşmadadır.",
    tetbiq: "Norma və gözləmə müddəti etiketə görə; çiləmə küləksiz havada.",
    elaveTarixi: "2026-08-05",
    populyarliq: 74,
    sekil: { nov: "yuva" },
  },
  {
    kod: "insektisid-1l",
    ad: "Geniş spektrli insektisid — 1 L",
    kateqoriya: "muhafize",
    tedarukcu: "aqrokimya",
    brend: "Aqrokimya",
    qiymet: 41,
    vahidKey: "qab",
    qablasma: "1 L, emulsiya konsentratı",
    minSay: 1,
    maxSay: 200,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: [...ARAN, ...QERB],
    bitkiler: ["pomidor", "kartof", "pambiq", "alma"],
    tesvir: "Sorucu və gəmirici zərərvericilərə qarşı. Reyestr nömrəsi qablaşmadadır.",
    tetbiq: "Norma və gözləmə müddəti etiketə görə.",
    elaveTarixi: "2026-08-05",
    populyarliq: 70,
    sekil: { nov: "yuva" },
  },
  {
    kod: "herbisid-taxil-5l",
    ad: "Taxıl üçün herbisid — 5 L",
    kateqoriya: "muhafize",
    tedarukcu: "aqrokimya",
    brend: "Aqrokimya",
    qiymet: 88,
    vahidKey: "qab",
    qablasma: "5 L kanistr",
    minSay: 1,
    maxSay: 100,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: [...ARAN, ...QERB],
    bitkiler: ["bugda", "arpa"],
    tesvir: "Taxıl əkinlərində ikiləpəli alaq otlarına qarşı seçici herbisid.",
    tetbiq: "Kollanma mərhələsində; norma etiketə görə.",
    elaveTarixi: "2026-08-05",
    populyarliq: 52,
    sekil: { nov: "yuva" },
  },
  {
    kod: "feromon-tele-10",
    ad: "Feromon tələ dəsti — 10 ədəd",
    kateqoriya: "muhafize",
    tedarukcu: "aqrokimya",
    brend: "BioAqro",
    qiymet: 27,
    vahidKey: "dest",
    qablasma: "10 tələ + 10 dispenser",
    minSay: 1,
    maxSay: 100,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: [...ARAN, ...QERB],
    bitkiler: ["alma", "uzum", "pomidor"],
    tesvir: "Zərərvericinin uçuş vaxtını izləmək üçün — çiləməni vaxtında etmək deməkdir.",
    tetbiq: "Hektara 2–4 tələ; dispenser 4–6 həftədən bir dəyişdirilir.",
    elaveTarixi: "2026-09-03",
    populyarliq: 33,
    sekil: { nov: "yuva" },
  },
  {
    kod: "bel-cileyicisi-16l",
    ad: "Bel çiləyicisi 16 L (akkumulyatorlu)",
    kateqoriya: "muhafize",
    tedarukcu: "ferma-market",
    brend: "FieldPro",
    qiymet: 145,
    vahidKey: "eded",
    qablasma: "16 L çən, litium akkumulyator, 3 uc",
    minSay: 1,
    maxSay: 20,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: ARAN,
    bitkiler: ["pomidor", "kartof", "uzum", "alma", "sogan"],
    tesvir: "Bir doluşla 4–6 saat iş. Zəmanət 1 il.",
    tetbiq: "Kiçik sahələr və bağlar üçün.",
    elaveTarixi: "2026-07-18",
    populyarliq: 69,
    sekil: { nov: "yuva" },
  },

  // ── Suvarma ────────────────────────────────────────────────────────────
  {
    kod: "damci-lenti-16mm-500m",
    ad: "Damcı suvarma lenti 16 mm — 500 m rulon",
    kateqoriya: "suvarma",
    tedarukcu: "suvarmatex",
    brend: "AquaLine",
    qiymet: 95,
    vahidKey: "rulon",
    qablasma: "500 m, damcı addımı 20 sm, 1,6 L/saat",
    minSay: 1,
    maxSay: 300,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["pomidor", "kartof", "sogan", "qargidali", "pambiq"],
    tesvir: "Bir mövsümlük lent; UV-yə davamlı. Hektara cərgə arasına görə 5–8 rulon.",
    tetbiq: "Filtr və təzyiq tənzimləyicisi ilə istifadə edilir.",
    elaveTarixi: "2026-08-12",
    populyarliq: 89,
    sekil: { nov: "yuva" },
  },
  {
    kod: "disk-filtr-2",
    ad: "Disk filtr 2″ (120 mesh)",
    kateqoriya: "suvarma",
    tedarukcu: "suvarmatex",
    brend: "AquaLine",
    qiymet: 140,
    vahidKey: "eded",
    qablasma: "2 düymlük, 120 mesh, 25 m³/saat",
    minSay: 1,
    maxSay: 50,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["pomidor", "kartof", "sogan", "uzum", "alma"],
    tesvir: "Damcı sisteminin əsas qoruyucusu — tıxanan damcılardan qorunma.",
    tetbiq: "Nasosdan sonra, əsas xəttin əvvəlində.",
    elaveTarixi: "2026-08-12",
    populyarliq: 57,
    sekil: { nov: "yuva" },
  },
  {
    kod: "pe-boru-32mm-100m",
    ad: "PE boru 32 mm — 100 m",
    kateqoriya: "suvarma",
    tedarukcu: "suvarmatex",
    brend: "AquaLine",
    qiymet: 78,
    vahidKey: "rulon",
    qablasma: "100 m rulon, PN6",
    minSay: 1,
    maxSay: 200,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: BUTUN_BITKILER,
    tesvir: "Paylayıcı xətt üçün polietilen boru.",
    tetbiq: "Fitinqlərlə birləşdirilir; torpaq üstü və altı.",
    elaveTarixi: "2026-08-12",
    populyarliq: 63,
    sekil: { nov: "yuva" },
  },
  {
    kod: "nasos-1-5kvt",
    ad: "Suvarma nasosu 1,5 kVt (mərkəzdənqaçma)",
    kateqoriya: "suvarma",
    tedarukcu: "suvarmatex",
    brend: "HydroMax",
    qiymet: 320,
    vahidKey: "eded",
    qablasma: "1,5 kVt, 220 V, 9 m³/saat",
    minSay: 1,
    maxSay: 10,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: BUTUN_BITKILER,
    tesvir: "1–2 ha damcı sistemi üçün. Zəmanət 2 il.",
    tetbiq: "Filtr və təzyiq tənzimləyicisi ilə birlikdə.",
    elaveTarixi: "2026-07-25",
    populyarliq: 71,
    sekil: { nov: "yuva" },
  },
  {
    kod: "fitinq-desti-100",
    ad: "Damcı fitinq dəsti — 100 ədəd",
    kateqoriya: "suvarma",
    tedarukcu: "suvarmatex",
    brend: "AquaLine",
    qiymet: 24,
    vahidKey: "dest",
    qablasma: "Start-konnektor, tıxac, birləşdirici — 100 ədəd",
    minSay: 1,
    maxSay: 100,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: "*",
    bitkiler: BUTUN_BITKILER,
    tesvir: "Lentin boruya bağlanması üçün standart dəst.",
    tetbiq: "16 mm lent üçün.",
    elaveTarixi: "2026-08-12",
    populyarliq: 48,
    sekil: { nov: "yuva" },
  },
  {
    kod: "yagis-cileyici-impuls",
    ad: "Yağış çiləyicisi (impuls, 3/4″)",
    kateqoriya: "suvarma",
    tedarukcu: "suvarmatex",
    brend: "AquaLine",
    qiymet: 18,
    vahidKey: "eded",
    qablasma: "Metal, radius 12–15 m",
    minSay: 1,
    maxSay: 200,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["bugda", "arpa", "qargidali", "findiq"],
    tesvir: "Taxıl və otlaq üçün yağış tipli suvarma.",
    tetbiq: "Ştativ və ya boru üzərində.",
    elaveTarixi: "2026-08-12",
    populyarliq: 36,
    sekil: { nov: "yuva" },
  },

  // ── Heyvandarlıq ───────────────────────────────────────────────────────
  {
    kod: "qarisiq-yem-40kq",
    ad: "Qarışıq yem (iribuynuzlu) — 40 kq",
    kateqoriya: "heyvandarliq",
    tedarukcu: "ferma-market",
    brend: "FermaYem",
    qiymet: 26,
    vahidKey: "kise",
    qablasma: "40 kq kisə, dənəvər",
    minSay: 5,
    maxSay: 500,
    stok: "var",
    maliyye: true,
    orijinal: false,
    rayonlar: ARAN,
    bitkiler: [],
    tesvir: "Süd istiqamətli mal-qara üçün balanslaşdırılmış yem.",
    tetbiq: "Gündəlik norma heyvanın çəkisinə görə.",
    elaveTarixi: "2026-08-01",
    populyarliq: 58,
    sekil: { nov: "yuva" },
  },
  {
    kod: "yonca-kulesi-ton",
    ad: "Yonca küləşi (preslənmiş) — 1 ton",
    kateqoriya: "heyvandarliq",
    tedarukcu: "ferma-market",
    brend: "Ferma Market",
    qiymet: 180,
    vahidKey: "ton",
    qablasma: "Kvadrat presslənmiş, ~20 kq/bağ",
    minSay: 1,
    maxSay: 40,
    stok: "var",
    maliyye: true,
    orijinal: false,
    rayonlar: ARAN,
    bitkiler: [],
    tesvir: "2026 biçini, quru saxlanılıb.",
    tetbiq: "Qış yem ehtiyatı.",
    elaveTarixi: "2026-07-05",
    populyarliq: 44,
    sekil: { nov: "yuva" },
  },
  {
    kod: "mineral-yalama-10kq",
    ad: "Mineral duz-yalama — 10 kq",
    kateqoriya: "heyvandarliq",
    tedarukcu: "ferma-market",
    brend: "FermaYem",
    qiymet: 12,
    vahidKey: "eded",
    qablasma: "10 kq blok",
    minSay: 1,
    maxSay: 100,
    stok: "var",
    maliyye: false,
    orijinal: false,
    rayonlar: ARAN,
    bitkiler: [],
    tesvir: "Mikroelementli yalama daşı.",
    tetbiq: "Otlaqda və tövlədə sərbəst giriş.",
    elaveTarixi: "2026-08-01",
    populyarliq: 30,
    sekil: { nov: "yuva" },
  },
  {
    kod: "sud-qabi-30l",
    ad: "Alüminium süd qabı — 30 L",
    kateqoriya: "heyvandarliq",
    tedarukcu: "ferma-market",
    brend: "Ferma Market",
    qiymet: 68,
    vahidKey: "eded",
    qablasma: "30 L, qapaqlı",
    minSay: 1,
    maxSay: 30,
    stok: "az",
    maliyye: false,
    orijinal: false,
    rayonlar: ARAN,
    bitkiler: [],
    tesvir: "Süd daşınması üçün standart bidon.",
    tetbiq: "",
    elaveTarixi: "2026-06-10",
    populyarliq: 22,
    sekil: { nov: "yuva" },
  },

  // ── Texnika və avadanlıq ───────────────────────────────────────────────
  {
    kod: "mini-traktor-25",
    ad: "Mini traktor 25 a.g. (4×4)",
    kateqoriya: "texnika",
    tedarukcu: "agrotexnika",
    brend: "AgroTrac",
    qiymet: 18500,
    vahidKey: "eded",
    qablasma: "Dizel, 4×4, arxa asqı, VOM",
    minSay: 1,
    maxSay: 3,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: BUTUN_BITKILER,
    tesvir: "Kiçik və orta təsərrüfat üçün; frez, kotan və qoşqu ilə uyğun. Zəmanət 2 il, servis Gəncə və Bakı.",
    tetbiq: "5–30 ha təsərrüfat.",
    elaveTarixi: "2026-05-15",
    populyarliq: 65,
    sekil: { nov: "yuva" },
  },
  {
    kod: "motoblok-9",
    ad: "Motoblok 9 a.g. (dizel)",
    kateqoriya: "texnika",
    tedarukcu: "agrotexnika",
    brend: "AgroTrac",
    qiymet: 1650,
    vahidKey: "eded",
    qablasma: "Dizel, frez 100 sm, elektrik start",
    minSay: 1,
    maxSay: 5,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["pomidor", "kartof", "sogan", "uzum", "alma"],
    tesvir: "Bağ və tərəvəz sahələri üçün. Zəmanət 1 il.",
    tetbiq: "0,5–5 ha təsərrüfat.",
    elaveTarixi: "2026-05-15",
    populyarliq: 72,
    sekil: { nov: "yuva" },
  },
  {
    kod: "asma-cileyici-400l",
    ad: "Asma çiləyici 400 L (traktor üçün)",
    kateqoriya: "texnika",
    tedarukcu: "agrotexnika",
    brend: "AgroTrac",
    qiymet: 2400,
    vahidKey: "eded",
    qablasma: "400 L çən, 8 m ştanq, VOM nasos",
    minSay: 1,
    maxSay: 3,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["bugda", "arpa", "qargidali", "pambiq", "kartof"],
    tesvir: "Sahə əkinləri üçün ştanqlı çiləyici.",
    tetbiq: "25 a.g.-dən yuxarı traktor tələb edir.",
    elaveTarixi: "2026-06-02",
    populyarliq: 41,
    sekil: { nov: "yuva" },
  },
  {
    kod: "kotan-2-govde",
    ad: "İki gövdəli kotan (asma)",
    kateqoriya: "texnika",
    tedarukcu: "agrotexnika",
    brend: "AgroTrac",
    qiymet: 780,
    vahidKey: "eded",
    qablasma: "2 gövdə, iş eni 50 sm",
    minSay: 1,
    maxSay: 3,
    stok: "var",
    maliyye: true,
    orijinal: true,
    rayonlar: "*",
    bitkiler: BUTUN_BITKILER,
    tesvir: "Mini traktor üçün şum kotanı.",
    tetbiq: "20–30 a.g. traktor.",
    elaveTarixi: "2026-06-02",
    populyarliq: 35,
    sekil: { nov: "yuva" },
  },

  // ── Aqro xidmətlər ─────────────────────────────────────────────────────
  {
    kod: "torpaq-analizi",
    ad: "Torpaq analizi (N-P-K, pH, duzluluq) — 1 sahə",
    kateqoriya: "xidmet",
    tedarukcu: "aqroxidmet",
    brend: "Aqro Xidmət",
    qiymet: 60,
    vahidKey: "xidmet",
    qablasma: "Nümunə götürmə + laboratoriya hesabatı",
    minSay: 1,
    maxSay: 10,
    stok: "var",
    maliyye: false,
    orijinal: false,
    rayonlar: [...QERB, "berde", "yevlax", "goranboy"],
    bitkiler: BUTUN_BITKILER,
    tesvir: "Gübrə normasını təxminlə yox, analizlə təyin edin. Hesabat 7 gün ərzində.",
    tetbiq: "Səpindən 3–4 həftə əvvəl.",
    elaveTarixi: "2026-08-30",
    populyarliq: 77,
    sekil: { nov: "yuva" },
  },
  {
    kod: "aqronom-baxisi",
    ad: "Aqronom sahə baxışı — 1 səfər",
    kateqoriya: "xidmet",
    tedarukcu: "aqroxidmet",
    brend: "Aqro Xidmət",
    qiymet: 80,
    vahidKey: "xidmet",
    qablasma: "Sahəyə səfər + yazılı tövsiyə",
    minSay: 1,
    maxSay: 10,
    stok: "var",
    maliyye: false,
    orijinal: false,
    rayonlar: [...QERB, "berde", "yevlax", "goranboy"],
    bitkiler: BUTUN_BITKILER,
    tesvir: "Xəstəlik/zərərverici diaqnozu və mühafizə planı. Preparat seçimi reyestrə görə.",
    tetbiq: "Siqnal görünəndə və ya mövsüm əvvəli.",
    elaveTarixi: "2026-08-30",
    populyarliq: 60,
    sekil: { nov: "yuva" },
  },
  {
    kod: "kombayn-xidmeti-ha",
    ad: "Kombayn xidməti (taxıl biçini) — 1 ha",
    kateqoriya: "xidmet",
    tedarukcu: "aqroxidmet",
    brend: "Aqro Xidmət",
    qiymet: 55,
    vahidKey: "ha",
    qablasma: "Biçin + yığım, hektar hesabı",
    minSay: 1,
    maxSay: 500,
    stok: "var",
    maliyye: true,
    orijinal: false,
    rayonlar: [...QERB, "berde", "yevlax", "goranboy"],
    bitkiler: ["bugda", "arpa"],
    tesvir: "İyun–iyul biçin mövsümü üçün əvvəlcədən sıraya yazılın.",
    tetbiq: "Tarix telefonla razılaşdırılır.",
    elaveTarixi: "2026-08-30",
    populyarliq: 68,
    sekil: { nov: "yuva" },
  },
  {
    kod: "sumlama-ha",
    ad: "Şumlama xidməti — 1 ha",
    kateqoriya: "xidmet",
    tedarukcu: "aqroxidmet",
    brend: "Aqro Xidmət",
    qiymet: 40,
    vahidKey: "ha",
    qablasma: "Dərin şum, hektar hesabı",
    minSay: 1,
    maxSay: 500,
    stok: "var",
    maliyye: true,
    orijinal: false,
    rayonlar: [...QERB, "berde", "yevlax", "goranboy"],
    bitkiler: BUTUN_BITKILER,
    tesvir: "Payız şumu — səpindən əvvəl.",
    tetbiq: "Tarix telefonla razılaşdırılır.",
    elaveTarixi: "2026-08-30",
    populyarliq: 64,
    sekil: { nov: "yuva" },
  },
  {
    kod: "dron-cileme-ha",
    ad: "Dron ilə çiləmə — 1 ha",
    kateqoriya: "xidmet",
    tedarukcu: "aqroxidmet",
    brend: "Aqro Xidmət",
    qiymet: 35,
    vahidKey: "ha",
    qablasma: "Aqro-dron, preparat fermerindir",
    minSay: 2,
    maxSay: 300,
    stok: "var",
    maliyye: false,
    orijinal: false,
    rayonlar: [...QERB, "berde", "yevlax", "goranboy"],
    bitkiler: ["bugda", "arpa", "qargidali", "pambiq", "kartof"],
    tesvir: "Nəm sahəyə traktor girmir — dron girir. Preparat fermer tərəfindən verilir.",
    tetbiq: "Küləksiz səhər saatları.",
    elaveTarixi: "2026-09-04",
    populyarliq: 49,
    sekil: { nov: "yuva" },
  },

  // ── Digər ──────────────────────────────────────────────────────────────
  {
    kod: "aqrotekstil-1-6x100",
    ad: "Aqrotekstil (örtük materialı) 1,6×100 m",
    kateqoriya: "diger",
    tedarukcu: "agrosupply",
    brend: "AgroSupply",
    qiymet: 65,
    vahidKey: "rulon",
    qablasma: "1,6 m × 100 m, 30 q/m²",
    minSay: 1,
    maxSay: 100,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["pomidor", "sogan", "kartof"],
    tesvir: "Şaxtadan qoruma və erkən şitil üçün ağ örtük.",
    tetbiq: "Şitil və erkən əkin dövründə.",
    elaveTarixi: "2026-08-22",
    populyarliq: 39,
    sekil: { nov: "yuva" },
  },
  {
    kod: "yigim-qutusu-10",
    ad: "Yığım qutusu 20 kq — 10 ədəd",
    kateqoriya: "diger",
    tedarukcu: "ferma-market",
    brend: "Ferma Market",
    qiymet: 38,
    vahidKey: "dest",
    qablasma: "Plastik, havalandırmalı, 10 ədəd",
    minSay: 1,
    maxSay: 100,
    stok: "var",
    maliyye: false,
    orijinal: false,
    rayonlar: ARAN,
    bitkiler: ["pomidor", "alma", "uzum", "kartof"],
    tesvir: "Məhsulun yığımı və daşınması üçün.",
    tetbiq: "",
    elaveTarixi: "2026-07-20",
    populyarliq: 45,
    sekil: { nov: "yuva" },
  },
  {
    kod: "torlu-kise-100",
    ad: "Torlu kisə 50 kq — 100 ədəd",
    kateqoriya: "diger",
    tedarukcu: "agrosupply",
    brend: "AgroSupply",
    qiymet: 22,
    vahidKey: "dest",
    qablasma: "100 ədəd, polipropilen tor",
    minSay: 1,
    maxSay: 200,
    stok: "var",
    maliyye: false,
    orijinal: true,
    rayonlar: "*",
    bitkiler: ["kartof", "sogan"],
    tesvir: "Kartof və soğan üçün havalandırmalı kisə.",
    tetbiq: "",
    elaveTarixi: "2026-07-20",
    populyarliq: 52,
    sekil: { nov: "yuva" },
  },
  {
    kod: "is-elceyi-10",
    ad: "İş əlcəyi (nitril) — 10 cüt",
    kateqoriya: "diger",
    tedarukcu: "ferma-market",
    brend: "Ferma Market",
    qiymet: 14,
    vahidKey: "dest",
    qablasma: "10 cüt, ölçü L",
    minSay: 1,
    maxSay: 100,
    stok: "var",
    maliyye: false,
    orijinal: false,
    rayonlar: ARAN,
    bitkiler: [],
    tesvir: "Dərmanlama və yığım üçün.",
    tetbiq: "",
    elaveTarixi: "2026-07-20",
    populyarliq: 28,
    sekil: { nov: "yuva" },
  },
];

const MEHSUL_XERITESI = new Map(MEHSULLAR.map((m) => [m.kod, m]));
const TEDARUKCU_XERITESI = new Map(TEDARUKCULER.map((s) => [s.kod, s]));
const KATEQORIYA_XERITESI = new Map(KATEQORIYALAR.map((k) => [k.kod, k]));

/** @returns {Mehsul|null} */
export function mehsulTap(kod) {
  return MEHSUL_XERITESI.get(kod) ?? null;
}

/** @returns {Tedarukcu|null} */
export function tedarukcuTap(kod) {
  return TEDARUKCU_XERITESI.get(kod) ?? null;
}

/** @returns {Kateqoriya|null} */
export function kateqoriyaTap(kod) {
  return KATEQORIYA_XERITESI.get(kod) ?? null;
}

export function kateqoriyaMehsullari(kod) {
  return MEHSULLAR.filter((m) => m.kateqoriya === kod);
}

export function tedarukcuMehsullari(kod) {
  return MEHSULLAR.filter((m) => m.tedarukcu === kod);
}

/**
 * Bu rayona çatdırılırmı. Məhsulun öz əhatəsi tədarükçününkündən DARDIR
 * (pambıq toxumu yalnız arana) — ikisi də yoxlanılır. Rayon məlum deyilsə
 * (fermer seçməyib) "bilinmir" — mövcud sayılır, amma etiket göstərilmir.
 */
export function rayonaCatdirilir(mehsul, rayonKod) {
  if (!mehsul) return false;
  if (!rayonKod) return true;
  const tedarukcu = tedarukcuTap(mehsul.tedarukcu);
  const ehate = (siyahi) => siyahi === "*" || (Array.isArray(siyahi) && siyahi.includes(rayonKod));
  return ehate(mehsul.rayonlar) && ehate(tedarukcu?.rayonlar ?? "*");
}

/** Çatdırılma pulsuzdur (tədarükçü haqqı 0) — kart nişanı üçün */
export function pulsuzCatdirilma(mehsul) {
  const tedarukcu = tedarukcuTap(mehsul?.tedarukcu);
  return Boolean(tedarukcu && tedarukcu.catdirilmaHaqqi === 0);
}
